# Generated by Django 4.1 on 2022-08-29 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='note1',
            field=models.TextField(max_length=200, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='note2',
            field=models.TextField(max_length=200, null=True, verbose_name='Extra Note'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='note3',
            field=models.TextField(max_length=200, null=True, verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='tar.section'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.TextField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code1',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='code2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='code3',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='code4',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='dach',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('num', 'number'), ('m2', 'square_meter'), ('m3', 'cube_meter'), ('kg', 'kilo_gram')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='note1',
            field=models.TextField(max_length=200, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='section',
            name='note2',
            field=models.TextField(max_length=200, null=True, verbose_name='Extra Note'),
        ),
        migrations.AlterField(
            model_name='section',
            name='note3',
            field=models.TextField(max_length=200, null=True, verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.TextField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
