# Generated by Django 4.1 on 2022-08-30 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tar', '0003_remove_chapter_title_item_chapter_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='chapter_id',
        ),
    ]
