# Generated by Django 4.1 on 2022-08-30 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tar', '0004_rename_title_chapter_title_remove_item_chapter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='chapter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tar.chapter'),
        ),
    ]
